@startuml System Architecture

!theme materia-outline
skinparam backgroundColor #EEEBDC

cloud "AWS/GCP/Azure" as CLOUD {
    node Grafana
    node Prometheus
    node Jaeger
    Grafana --> Prometheus
    node FrontEnd
    Prometheus -> FrontEnd
    node MemCache
    FrontEnd --> MemCache
    Prometheus -> MemCache
    node BackEnd
    FrontEnd ---> BackEnd
    Prometheus -> BackEnd
    database Storage
    Prometheus -> Storage
    BackEnd --> Storage
    database Traces
    BackEnd --> Traces
    FrontEnd ---> Traces
    Jaeger <---- Traces
}
actor User
User ---> FrontEnd
actor SRE
SRE --> Grafana
SRE --> Jaeger
@enduml