apiVersion: v1
kind: Pod
metadata:
  name: demostack-frontend
  labels:
    release: "prometheus"
    app: "demostack"

spec:
  containers:
    - name: frontend-app
      image: europe-north1-docker.pkg.dev/lets-get-it-started-384609/demostack/frontend:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8082
          name: "web"
        - containerPort: 9000
          name: "http-metrics"
      resources:
        limits:
          cpu: "1"
          memory: "300Mi"
