apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cartvalue
  namespace: mon
  labels:
    team: frontend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: demostack
  endpoints:
    - port: http-metrics
