kind: Service
apiVersion: v1
metadata:
  name: cartvalue
  namespace: mon
  labels:
    app: demostack
    release: prometheus
spec:
  selector:
    app: demostack
  ports:
    - name: http-metrics
      port: 9000
      targetPort: 9000